version: "2"

plugins:
  - name: "kt"
    wasm:
      url: "https://downloads.sqlc.dev/plugin/sqlc-gen-kotlin_1.1.0.wasm"
      sha256: "57890144f4effed4fe71855418b87ad26d53dc5ed2030a66ad77e5e3a93d77fb"
sql:
  - schema: "schema.sql"
    queries: "queries"
    engine: "postgresql"
    codegen:
      - out: "../../src/main/kotlin/br/com/abc/def/infra/db/schema"
        plugin: "kt"
        options:
          package: "br.com.abc.def.infra.db.schema"
