/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package br.com.abc.def

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test
    fun `app should have a greeting`() {
        val classUnderTest = App()
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }
}
