// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package br.com.abc.def.infra.db.schema

import java.sql.SQLException

interface Queries {
  @Throws(SQLException::class) fun getPerson(id: Long): Person?
}
