/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.2.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
  // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
  id("org.jetbrains.kotlin.jvm") version "1.8.20"

  // Apply the application plugin to add support for building a CLI application in Java.
  application

  // CI
  jacoco
  id("io.gitlab.arturbosch.detekt") version "1.23.0"
  id("com.ncorti.ktfmt.gradle") version "0.12.0"
}

version = "0.1"
group = "br.com.abc"

val appMainClass = "br.com.abc.def.AppKt"

// Dependencies versions.
val beamVersion = "2.49.0"

repositories {
  // Use Maven Central for resolving dependencies.
  mavenCentral()

  maven {
    url = uri("https://packages.confluent.io/maven/")
  }
}

dependencies {
  // Kotlin dependencies.
  implementation(platform("org.jetbrains.kotlin:kotlin-bom"))
  implementation("org.jetbrains.kotlin:kotlin-stdlib")

  // Test dependencies.
  testRuntimeOnly("org.junit.platform:junit-platform-launcher")
  testImplementation("org.jetbrains.kotlin:kotlin-test-junit5")
  testImplementation("org.junit.jupiter:junit-jupiter-engine:5.9.2")
  testImplementation("io.mockk:mockk:1.13.5")
  testImplementation("io.kotest:kotest-assertions-core:5.6.2")
  testImplementation("com.tngtech.archunit:archunit:1.0.1")

  // App dependencies.
  implementation("org.slf4j:slf4j-api:2.0.7")
  implementation("ch.qos.logback:logback-classic:1.4.8")
  implementation("com.google.guava:guava:31.1-jre")
  implementation("org.postgresql:postgresql:42.6.0")
  implementation("com.zaxxer:HikariCP:5.0.1")

  // Apache Beam
  implementation("org.apache.beam:beam-sdks-java-core:${beamVersion}")
  implementation("org.apache.beam:beam-runners-direct-java:${beamVersion}")
  implementation("org.slf4j:slf4j-jdk14:2.0.7")

  // GCP
  implementation("com.google.cloud:google-cloud-logging-logback:0.130.17-alpha")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
  toolchain {
    languageVersion.set(JavaLanguageVersion.of(17))
  }
}

application {
  // Define the main class for the application.
  mainClass.set(appMainClass)
}

jacoco {
  toolVersion = "0.8.10"
}

detekt {
  toolVersion = "1.23.0"
  config.setFrom(file("config/detekt/detekt.yml"))
  buildUponDefaultConfig = true
}

tasks.named<Test>("test") {
  // Use JUnit Platform for unit tests.
  useJUnitPlatform()

  maxHeapSize = "512m"

  finalizedBy(tasks.named("jacocoTestReport"))
}

tasks.named<JacocoReport>("jacocoTestReport") {
  dependsOn(tasks.named("test"))

  reports {
    xml.required.set(true)
    csv.required.set(false)
    html.required.set(true)
  }
}

tasks.named<JacocoCoverageVerification>("jacocoTestCoverageVerification") {
  violationRules {
    rule {
      element = "SOURCEFILE"
      limit {
        minimum = "0.0".toBigDecimal()
      }
    }
  }
}

// Package a self-contained jar file.
tasks.jar {
  archiveBaseName.set("app")
  destinationDirectory.set(file("build"))
  manifest { attributes("Main-Class" to appMainClass) }
  exclude("META-INF/*.SF")
  exclude("META-INF/*.DSA")
  exclude("META-INF/*.RSA")
  duplicatesStrategy = DuplicatesStrategy.EXCLUDE
  from({ configurations.runtimeClasspath.get().map(::zipTree) })
}
