version: "3"

networks:
  service_network:
    external: false

services:
  postgres:
    image: postgis/postgis:13-3.3-alpine
    container_name: discovery
    environment:
      - POSTGRES_DB=docker
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    ports:
      - "5432:5432"
    volumes:
      - ".docker/postgres:/var/lib/postgresql/data"
    networks:
      - service_network
