version: "3"

vars:
  APP_DIR: "{{.USER_WORKING_DIR}}/app"
  BUILD_DIR: "{{.USER_WORKING_DIR}}/app/build"
  BIN_DIR: "{{.USER_WORKING_DIR}}/bin"

env:
  APP_ENV: dev

dotenv: [".env"]

tasks:
  download:
    cmds:
      - mkdir -p {{.BIN_DIR}}
      - curl -L https://github.com/hguerra/envsubst/releases/download/v1.0.6/envsubst_linux_amd64 -o ./bin/envsubst && chmod +x ./bin/envsubst
      - curl -L https://release.ariga.io/atlas/atlas-linux-amd64-latest -o ./bin/atlas && chmod +x ./bin/atlas
      - curl -L https://downloads.sqlc.dev/sqlc_1.19.1_linux_amd64.tar.gz -o ./bin/sqlc.tar.gz && tar -xzvf ./bin/sqlc.tar.gz -C ./bin/ && rm -rf ./bin/sqlc.tar.gz && chmod +x ./bin/sqlc

  clean:
    cmds:
      - ./gradlew clean

  build:
    cmds:
      - ./gradlew build

  assemble:
    cmds:
      - ./gradlew assemble

  assembleOffiline:
    cmds:
      - ./gradlew --offline assemble

  lint:
    cmds:
      -  ./gradlew ktfmtCheck
      -  ./gradlew detekt

  format:
    cmds:
      - ./gradlew ktfmtFormat

  test:
    cmds:
      - ./gradlew test

  run:
    cmds:
      - ./gradlew run

  runArgs:
    cmds:
      - ./gradlew run --args=--inputText="🎉"

  runJar:
    cmds:
      - ./gradlew jar
      - java -jar app/build/app-0.1.jar

  dbUp:
    cmds:
      - docker compose up -d

  dbDown:
    cmds:
      - docker compose down

  dbInspect:
    cmds:
      - bin/atlas schema inspect -c file://app/config/db/atlas.hcl --env ${APP_ENV}

  dbCreateSeed:
    cmds:
      - bin/atlas migrate new {{.CLI_ARGS}} -c file://app/config/db/atlas.hcl --env ${APP_ENV}

  dbCreateMigration:
    cmds:
      - bin/atlas migrate diff {{.CLI_ARGS}} -c file://app/config/db/atlas.hcl --env ${APP_ENV}

  dbMigrate:
    cmds:
      - bin/atlas migrate apply -c file://app/config/db/atlas.hcl --env ${APP_ENV}
      - bin/atlas schema inspect --format "{{`{{ sql . }}`}}" -c file://app/config/db/atlas.hcl --exclude "atlas_schema_revisions" --env ${APP_ENV} > ./app/config/db/schema.sql

  dbUpdateMigrationHash:
    cmds:
      - bin/atlas migrate hash -c file://app/config/db/atlas.hcl --env ${APP_ENV}

  dbValidate:
    cmds:
      - bin/atlas migrate validate -c file://app/config/db/atlas.hcl --env ${APP_ENV}

  dbLint:
    cmds:
      - bin/atlas migrate lint -c file://app/config/db/atlas.hcl --env ${APP_ENV}

  dbGenerateCode:
    cmds:
      - bin/sqlc -f app/config/db/sqlc.yaml generate
